# Production image (TC-OPS-01, ADR-0002/0005): one container serves both the
# API and the SPA statics. Configuration comes exclusively from env vars
# (DATABASE_URL, PORT) — no secrets baked in (NFR-SEC-04).

# ---- build stage -----------------------------------------------------------
FROM node:22-slim AS build
ENV NX_DAEMON=false
WORKDIR /repo

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
# api build emits dist/api plus a pruned package.json/package-lock.json
# (webpack generatePackageJson) used by the runtime stage
RUN npx prisma generate \
  && npx nx build web \
  && npx nx build api

# ---- runtime stage ---------------------------------------------------------
FROM node:22-slim
ENV NODE_ENV=production
# Prisma CLI (migrate deploy) may need openssl on Debian slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Pruned manifest generated by the api build (only runtime deps), plus:
# - @prisma/client: deep-imported by the generated client at runtime but
#   missed by webpack's manifest; keep the version in sync with package.json
# - prisma CLI: `migrate deploy` on startup (design D6)
COPY --from=build /repo/dist/api/package.json /repo/dist/api/package-lock.json ./
RUN npm ci --omit=dev \
  && npm install --no-save @prisma/client@7.8.0 prisma@7.8.0 \
  && npm cache clean --force

COPY --from=build /repo/dist/api ./api
COPY --from=build /repo/dist/web ./web
COPY --from=build /repo/prisma.config.ts ./
COPY --from=build /repo/api/prisma ./api/prisma

EXPOSE 3000
# Apply pending migrations, then start; safe with the single-instance
# constraint (TC-MEDIA-01)
CMD ["sh", "-c", "npx prisma migrate deploy && node api/main.js"]
